# Related scripts
train_script_name: common
module_script_name: uie
class_name: UIE

# Model Configuration
feature_num: 32

module_params:
  upsampling: 4
  bias: True
  window_size: 4
# Training information
total_epoch: 300

# Dataset
dataloader: UFO120
dataset_name: UFO120 
batch_size: 32
random_seed: 1234
dataset_params:
  lr_patch_size: 64
  image_scale: 4
  subffix: jpg
  dataloader_workers: 1
  dataset_enlarge: 64
  color_jitter: False
  color_config:
    brightness: 0.02
    contrast:   0.02
    saturation: 0.02
    hue:        0.02
  enable_reshuffle: False

# eval_dataloader: memory
# eval_dataset_name: urban100
eval_batch_size: 1

# Optimizer
lr_decay: 0.5
lr_decay_step: [250, 500, 750, 1000]
lr_decay_enable: True
optim_type: AdamW
optim_config:
  lr: !!float 5e-4
  betas: [0.9, 0.999]
  weight_decay: !!float 1e-4

# Losses
l1_weight: 1.0

# Log 
log_step: 200
sample_step: 200
model_save_epoch: 1
checkpoint_names:
  generator_name: UIE